### ISSUE TITLE
Code Injection

### ISSUE THREAD

**Issue by Light-Wizzard** [cutelyst/CMlyst#14]
Not sure how this is suppose to work; but currently the header will print above and below the content; and the footer does not print at all.

**Comment by dantti** [comment]
In `themes/default/base.html` you have `{{cms_head}}` and `{{cms_foot}}` that is replaced by the HTML code you fill in that option

**Comment by Light-Wizzard** [comment]
This should not be closed; its an Issue: to duplicate this issue; put code in both header and footer;
I used this for my test:
CMS Header
<style> body {  background-color: lightblue; } </style>
CMS Footer
<style>  body {  background-color: white; }  </style>

I would expect to see a white background and not a lightblue one; since the Footer in the footer will change it; but I see the same body css as is in the header, its duplicated the two.

I did find the references to {{cms_head}} and {{cms_foot}} in the base.html template; and adminsettings.cpp and root.cpp
where on line 98 I see this:
`
    const QString cms_foot = settings.value(QStringLiteral("cms_head"));
    if (!cms_foot.isEmpty()) {
        const Grantlee::SafeString safe(cms_foot, true);
        c->setStash(QStringLiteral("cms_foot"), QVariant::fromValue(safe));
    }
`
which should be this:

`
const QString cms_foot = settings.value(QStringLiteral("cms_foot"));
`

and at line 283

`
const QString cms_foot = settings.value(QStringLiteral("cms_head"));
`

same thing:

`
const QString cms_foot = settings.value(QStringLiteral("cms_foot"));
`

I need to learn how to do pushes; I will work on getting this into my github.

**Comment by Light-Wizzard** [comment]
My bad; I learned how to do a pull request.
