### ISSUE TITLE
CMlyst exit immediately

### ISSUE THREAD

**Issue by cezaryece** [cutelyst/CMlyst#25]
Build without any changes in code.
I only have few lines of messages:

7803:7803 cutelyst.core[warning] Can not load translations from not existing directory: "/usr/share/cutelyst3/translations"
7803:7803 default[warning] QThread::setEventDispatcher: An event dispatcher has already been created for this thread
Cutelyst-Server starting
Installing EPoll event loop
*** WARNING: you are running Cutelyst-Server without its master process manager ***
Cutelyst-Server terminated

Process finished with exit code 1

I found that CMlyst class is created, but CMlyst::Init() is never called.

**Comment by dantti** [comment]
did you specify which port to listen to?
