### ISSUE TITLE
Cannot create a user

### ISSUE THREAD

**Issue by Light-Wizzard** [cutelyst/CMlyst#4]
After creating a SETUP environment variable: declare -x SETUP=true
I get this Error:
cutelyst.utils.sql[critical] Failed to prepare query: "INSERT OR REPLACE INTO users (name, email, password) VALUES (:name, :email, :password)" "table users has no column named name"
I verified the cmlyst.sqlite database only had 5 fields:
id
slug
email
password
json
sqluserstore.h seems to be where the call came from: bool SqlUserStore::addUser
setup.html is where the form data is located.
cmlyst.cpp calls adminsetup.cpp via AdminSetup, 
sqlengine.cpp is where the create script seems to come from.
"CREATE TABLE users "
                                   "( id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT "
                                   ", slug TEXT NOT NULL UNIQUE "
                                   ", email TEXT NOT NULL UNIQUE "
                                   ", password TEXT NOT NULL "
                                   ", json TEXT "
                                   ")"))) {
and as you can see, there is no name field.
adding:
", name TEXT NOT NULL UNIQUE "
gave me another error:
Failed to add new user: "NOT NULL constraint failed: users.slug"
which lead me to believe that name was suppose to map to slug, 
I noticed that username maps to name, 
bool ret = store->addUser({
                                              {QStringLiteral("name"), username},
                                              {QStringLiteral("email"), email},
                                              {QStringLiteral("password"), password},
                                          });
Since slug TEXT NOT NULL UNIQUE, it can not be sent to addUser without adding it.

I do not know enough about this function to fix it, it seems you need to fix a few things in order for this to work right, name looks like it was added to the function as an after thought and was not finished, my guess is that slug is used as username, in the code name is not used much but slug is, but the use of slug is normally used for specific reasons: http://codex.wordpress.org/Glossary#Slug, not sure how this relates to this function, but my guess is that its based on WordPress, but its obvious that name needs to be added unless it converts to slug, in which the names need to be fixed, but it seems to me that is not the case and name needs to be added to the database and slug needs to be populated from data collected, like Full Name, but a Slug is normally a one liner describing that person, and is normally used in signatures in posts. 

I hope I gave enough information to resolve this issue.

**Comment by dantti** [comment]
Thanks, slug here was added after I started mimicking Ghost, this is the name used in the URL of the author, like /.author/slug_of_the_author.
For the name the thing is that I decided to store extra information in JSON format, not very flexible due sqlite storing it as text but since it's an information that is small I cache this.
Also since the SETUP is used only once I forgot to test it before release, will update this ASAP.
