### ISSUE TITLE
Admin Menu app crashes when you add a new menu item

### ISSUE THREAD

**Issue by Light-Wizzard** [cutelyst/CMlyst#7]
I create a new menu, and give it a name, and then a name for the Menu Item and a Url, it crashes the app:
appending "About" "http://domain.com/about.html"
Segmentation fault
I tried it without the .html extension and it does not matter.
The Item was there after restarting the program.
Editing the same Menu will also cause this problem.

**Comment by dantti** [comment]
are you using master? I'll try to reproduce, can you run it under a debugger to see where it's crashing?

**Comment by Light-Wizzard** [comment]
I did a git clone of the master (git clone https://github.com/cutelyst/CMlyst.git, then git pull today to make sure I had the latest), so I assume it is the latest.

I am an Old C++ programmer from the late 70's, most of my work has been in the U.S. Military and Government, and they do not use C++ much, but I did, I just like it better then other languages.

I am new to using Qtcreator with CMakeLists.txt, I opened it, defaults had Debug and Release, did a build and it seems to work, I see all the source files and headers, and it compiles with no errors, in the Run I picked the Debug, pointed it to the debug folder and object, set the Arguments: --http-socket :3000 --ini cmlyst.conf --chdir parent_of_root_dir --static-map /static=root/static (the ones I actually use and not these exactly, I figure I did not need all the arguments to cutelyst-wsgi, note that without them I get the same error, so I am doing something wrong) and when I run it I get an error and the disassemble, which tells me the arguments are not working, then I got to thinking that maybe it needs cutelyst-wsgi to run, coming from Wt, that was not the case, but its been a long day, and I had to give blood for a doctors appointment I have tomorrow, so after a 130 mile trip to the doctors wore me out, so my brain is not running all that well, so can you explain how you debug this App? 
I did not see a debug switch for cutelyst-wsgi, and I have no idea if I can pass it in as a Run Argument, I tried and it did not like that either, same error, I think this is why I like .pro files, but I think it only saves the run arguments in the user file, so I always need to know what those are, and I could not find that information anywhere, gdb does not seem like the right tool to debug Qt apps when you can use Qtcreator, but its easier to ask then try to spend all day trying things, thanks.

**Comment by dantti** [comment]
Fixed this, thanks.

To debug I run cutelyst-wsgi under gdb, QtCreator uses it under the hood as it's only an IDE.
