### ISSUE TITLE
Admin adding Post or Page, the Path does not allow access

### ISSUE THREAD

**Issue by Light-Wizzard** [cutelyst/CMlyst#8]
I create a new Post or Page, I enter a path: 
http://domain.com/home
or 
http://domain.com/home.html
I cannot access the page using the path, also the the example given about as such:
http://domain.com/2017/07/11
on first save the path gets messed up:
http://domian.com/third-post
becomes
2017/07/11/httpdomin-comthird-post
causing me to have to edit it,
and http://domian.com/third-post gives me a Page not found!

**Comment by dantti** [comment]
please confirm it works now. Thanks.
